### ISSUE TITLE
 Introducing Our 3D Semantic Occupancy Networks

### ISSUE THREAD

**Issue by jmwang0117** [HuaiyuanXu/3D-Occupancy-Perception#5]
Thank you for your excellent work! Could you please incorporate our 3D Semantic Occupancy Networks (_i.e., SCONet, LBSCNet, and OccMamba_) into the README.md or the relevant paper? These networks have been meticulously crafted for aerial-ground vehicles and stand poised to transform occupancy perception in intricate surroundings, thereby enhancing the operational efficiency and safety of autonomous navigation systems for air-ground vehicles. 

1. **SCONet**: Featured in our **[ICRA 2024]** publication "AGRNav: Efficient and Energy-Saving Autonomous Navigation for Air-Ground Robots in Occlusion-Prone Environments". 
**Code:** [AGRNav on GitHub](https://github.com/jmwang0117/AGRNav).

2. **LBSCNet**: As part of our **[RA-L 2024]** initiative, we present "HE-Nav: A High-Performance and Efficient Navigation System for Aerial-Ground Robots in Cluttered Environments". 
**project homepage:** [HE-Nav Project](https://jmwang0117.github.io/HE-Nav/).

3. **OccMamba**: Our work featured on **[arXiv 2024]** titled "OMEGA: Efficient Occlusion-Aware Navigation for Air-Ground Robot in Dynamic Environments via State Space Model". 
**project homepage:** [OMEGA Project](https://jmwang0117.github.io/OMEGA/).

These three networks exemplify the forefront of LiDAR-centric occupancy perception, poised to be pivotal in aerial-ground vehicles applications.

**Comment by HuaiyuanXu** [comment]
Thank you for your kind words and for sharing your remarkable work with us.

I'm delighted to let you know that we've included the three mentioned projects—AGRNav, HE-Nav, and OMEGA—into the README.md under the newly established "Navigation" section within the "Occupancy-based Applications". We hope this inclusion would enhance visibility of these projects among researchers and engineers, thereby advancing their impact.
